"""add weekend and holiday flags to schedule exceptions

Revision ID: 175299cc2518
Revises: 5b8e049202e9
Create Date: 2025-06-13 13:43:53.410631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175299cc2518'
down_revision: Union[str, None] = '5b8e049202e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_exceptions', sa.Column('include_saturday', sa.Boolean(), nullable=True))
    op.add_column('schedule_exceptions', sa.Column('include_sunday', sa.Boolean(), nullable=True))
    op.add_column('schedule_exceptions', sa.Column('include_holiday', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_exceptions', 'include_holiday')
    op.drop_column('schedule_exceptions', 'include_sunday')
    op.drop_column('schedule_exceptions', 'include_saturday')
    # ### end Alembic commands ###
