"""add schedule stops

Revision ID: 340f7591b39e
Revises: f70bdf0d27c4
Create Date: 2025-04-11 20:25:54.927926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '340f7591b39e'
down_revision: Union[str, None] = 'f70bdf0d27c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['shuttle_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_stops_id'), 'schedule_stops', ['id'], unique=False)
    op.drop_column('shuttle_station_routes', 'station_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shuttle_station_routes', sa.Column('station_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_schedule_stops_id'), table_name='schedule_stops')
    op.drop_table('schedule_stops')
    # ### end Alembic commands ###
