"""Add notices table

Revision ID: 3bda27f31284
Revises: a804da6b8e60
Create Date: 2025-04-01 19:58:37.105344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bda27f31284'
down_revision: Union[str, None] = 'a804da6b8e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_index(op.f('ix_notices_title'), 'notices', ['title'], unique=False)
    op.create_table('shuttle_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('UP', 'DOWN', name='direction_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_routes_id'), 'shuttle_routes', ['id'], unique=False)
    op.create_table('shuttle_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_stations_id'), 'shuttle_stations', ['id'], unique=False)
    op.create_table('shuttle_station_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['shuttle_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['shuttle_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shuttle_station_routes_id'), 'shuttle_station_routes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shuttle_station_routes_id'), table_name='shuttle_station_routes')
    op.drop_table('shuttle_station_routes')
    op.drop_index(op.f('ix_shuttle_stations_id'), table_name='shuttle_stations')
    op.drop_table('shuttle_stations')
    op.drop_index(op.f('ix_shuttle_routes_id'), table_name='shuttle_routes')
    op.drop_table('shuttle_routes')
    op.drop_index(op.f('ix_notices_title'), table_name='notices')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    # ### end Alembic commands ###
