"""initial migration

Revision ID: 4ea85e2a8679
Revises: 
Create Date: 2025-05-02 02:47:28.541883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea85e2a8679'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_exceptions', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('schedule_exceptions', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_exceptions', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('schedule_exceptions', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
