"""Add notice_type field to notices table

Revision ID: 5b8e049202e9
Revises: 52ce729b8a79
Create Date: 2025-05-26 12:16:09.950580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8e049202e9'
down_revision: Union[str, None] = '52ce729b8a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('notice_type', sa.Enum('APP', 'UPDATE', 'SHUTTLE', 'CITYBUS', name='noticetype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'notice_type')
    # ### end Alembic commands ###
