"""Add include_weekday field to schedule_exceptions

Revision ID: 62607c543e63
Revises: 175299cc2518
Create Date: 2025-06-13 14:46:18.094861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62607c543e63'
down_revision: Union[str, None] = '175299cc2518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_exceptions', sa.Column('include_weekday', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_exceptions', 'include_weekday')
    # ### end Alembic commands ###
