"""Add subway_schedules table

Revision ID: 724cf9e70448
Revises: 62607c543e63
Create Date: 2026-01-02 15:29:34.700699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724cf9e70448'
down_revision: Union[str, None] = '62607c543e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subway_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_no', sa.String(length=20), nullable=True),
    sa.Column('up_down_type', sa.String(length=10), nullable=True),
    sa.Column('day_type', sa.String(length=10), nullable=True),
    sa.Column('line_name', sa.String(length=20), nullable=True),
    sa.Column('branch_name', sa.String(length=20), nullable=True),
    sa.Column('station_name', sa.String(length=50), nullable=True),
    sa.Column('departure_station', sa.String(length=50), nullable=True),
    sa.Column('arrival_station', sa.String(length=50), nullable=True),
    sa.Column('departure_time', sa.String(length=10), nullable=True),
    sa.Column('arrival_time', sa.String(length=10), nullable=True),
    sa.Column('is_express', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subway_schedules_id'), 'subway_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_subway_schedules_train_no'), 'subway_schedules', ['train_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subway_schedules_train_no'), table_name='subway_schedules')
    op.drop_index(op.f('ix_subway_schedules_id'), table_name='subway_schedules')
    op.drop_table('subway_schedules')
    # ### end Alembic commands ###
