"""Create new tables

Revision ID: a57112c3dbdd
Revises: 
Create Date: 2025-03-07 01:43:51.592685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57112c3dbdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=True),
    sa.Column('route_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_routes_id'), 'bus_routes', ['id'], unique=False)
    op.create_index(op.f('ix_bus_routes_route_id'), 'bus_routes', ['route_id'], unique=True)
    op.create_index(op.f('ix_bus_routes_route_name'), 'bus_routes', ['route_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bus_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bus_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.route_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_locations_id'), 'bus_locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bus_locations_id'), table_name='bus_locations')
    op.drop_table('bus_locations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bus_routes_route_name'), table_name='bus_routes')
    op.drop_index(op.f('ix_bus_routes_route_id'), table_name='bus_routes')
    op.drop_index(op.f('ix_bus_routes_id'), table_name='bus_routes')
    op.drop_table('bus_routes')
    # ### end Alembic commands ###
