"""Add description and extra fields to shuttle_stations

Revision ID: f70bdf0d27c4
Revises: 3a7de1b904a8
Create Date: 2025-04-11 18:58:50.014156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70bdf0d27c4'
down_revision: Union[str, None] = '3a7de1b904a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shuttle_stations', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('shuttle_stations', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shuttle_stations', 'image_url')
    op.drop_column('shuttle_stations', 'description')
    # ### end Alembic commands ###
